/**
 * §3.2 opaque selector/verifier identifier and the `SC-191-001` peppered,
 * constant-time digest comparison.
 *
 * `SC-191-001` (Binding): "No code path may resolve a session by scanning or
 * comparing raw verifier values; only the selector-indexed, peppered-digest
 * comparison ... is a valid resolution path." This module is the *only*
 * place a verifier is hashed or compared. `verify()` never accepts a raw
 * verifier from anywhere but the caller's own cookie-parsed value, and it
 * never does a database scan -- callers look the row up by `selector` first
 * (see `resolve.ts`) and pass this module only the one candidate row's
 * stored digest.
 */
import { randomBytes, randomInt, timingSafeEqual, createHmac } from "node:crypto";

const RANDOM_BYTES = 32; // >= 256 bits, matching the CBD-190 challenge-material floor (§3.2).
// 32 bytes of unpadded base64url is always exactly 43 characters
// (ceil(256 bits / 6 bits-per-char)). CBD191-REVIEW-IMPL-001 Medium finding:
// an earlier revision accepted any base64url-charset string of any length as
// "well formed," so a short guessed half passed shape validation. Both
// halves generated by this module are always exactly this shape; resolution
// now enforces it exactly (see `parseCookieValue`).
const ENCODED_HALF_LENGTH = 43;
const HALF_PATTERN = new RegExp(`^[A-Za-z0-9_-]{${ENCODED_HALF_LENGTH}}$`);

export interface OpaqueIdentifier {
  readonly selector: string;
  readonly verifier: string;
  readonly cookieValue: string;
}

function randomToken(): string {
  return randomBytes(RANDOM_BYTES).toString("base64url");
}

/** Generates a new selector/verifier pair and the cookie value `<selector>.<verifier>` (§3.2). */
export function generateOpaqueIdentifier(): OpaqueIdentifier {
  const selector = randomToken();
  const verifier = randomToken();
  return { selector, verifier, cookieValue: `${selector}.${verifier}` };
}

export interface ParsedCookieValue {
  readonly selector: string;
  readonly verifier: string;
}

/**
 * §3.3 case 1: a malformed cookie (missing separator, wrong length, invalid
 * encoding) is never distinguished from any other rejection outcome by the
 * caller, but this function itself returns `undefined` rather than throwing,
 * so `resolve.ts` can still perform the same fixed-shape synthetic work
 * `SC-191-001A` requires instead of short-circuiting.
 */
export function parseCookieValue(raw: string | undefined): ParsedCookieValue | undefined {
  if (typeof raw !== "string") return undefined;
  const index = raw.indexOf(".");
  if (index <= 0 || index === raw.length - 1) return undefined;
  const selector = raw.slice(0, index);
  const verifier = raw.slice(index + 1);
  if (verifier.indexOf(".") !== -1) return undefined;
  if (!HALF_PATTERN.test(selector) || !HALF_PATTERN.test(verifier)) return undefined;
  return { selector, verifier };
}

/** Keyed (peppered) digest of a verifier or CSRF value. Never stores or logs the raw input. */
export function pepperedDigest(pepper: Buffer, value: string): string {
  return createHmac("sha256", pepper).update(value, "utf8").digest("base64url");
}

/**
 * Constant-time comparison of a candidate verifier's peppered digest against
 * the stored digest. `SC-191-001`: this is the *only* verification path;
 * nothing else in this package compares verifier material.
 */
export function verifyPepperedDigest(pepper: Buffer, candidate: string, storedDigest: string): boolean {
  const candidateDigest = Buffer.from(pepperedDigest(pepper, candidate), "utf8");
  const stored = Buffer.from(storedDigest, "utf8");
  if (candidateDigest.length !== stored.length) {
    // Still perform a same-shaped comparison so a length mismatch does not
    // return faster than a full compare (SC-191-001A's uniform-timing intent
    // extended down to this primitive).
    timingSafeEqual(candidateDigest, candidateDigest);
    return false;
  }
  return timingSafeEqual(candidateDigest, stored);
}

/** A synthetic selector/verifier pair used by `resolve.ts` for a malformed
 * cookie (§3.3 case 1), so a fixed-shape digest computation still runs. */
export function syntheticCandidate(): ParsedCookieValue {
  return { selector: randomToken(), verifier: randomToken() };
}

/** Generates an unpredictable, session-bound CSRF value (§5.1). */
export function generateCsrfValue(): string {
  return randomToken();
}

/** Generates an independent random `sessionRef` (§3.1, CBD191-SECURITY-002
 * High finding 2): a safe correlation identifier, never a cookie half. */
export function generateSessionRef(): string {
  return randomToken();
}

/**
 * `SC-191-001A`: cryptographically random jitter in `[0, maxMs]`, inclusive.
 * CBD191-REVIEW-IMPL-001 High finding: an earlier revision used
 * `Math.random()`, which is not a cryptographic source and is therefore not
 * a safe timing-side-channel mitigation.
 */
export function cryptoRandomJitterMs(maxMs: number): number {
  if (maxMs <= 0) return 0;
  return randomInt(0, maxMs + 1);
}
