import assert from "node:assert/strict";
import { test } from "node:test";

import type { MigrationFile } from "./catalog.ts";
import { checksumOf, normalizeForChecksum } from "./catalog.ts";
import { applyScript, parseAppliedRows, planApply, quoteLiteral, readAppliedScript } from "./plan.ts";
import { loadPolicy } from "./policy.ts";

const policy = loadPolicy();

function migration(ordinal: string, slug: string, body: string): MigrationFile {
  const bytes = Buffer.from(body, "utf8");
  return {
    fileName: `${ordinal}__${slug}.sql`,
    ordinal,
    slug,
    path: `/fake/${ordinal}__${slug}.sql`,
    source: body,
    bytes,
    checksum: checksumOf(bytes),
  };
}

const first = migration("20260101T000000Z", "one", "CREATE TABLE a (id uuid);\n");
const second = migration("20260201T000000Z", "two", "CREATE TABLE b (id uuid);\n");
const third = migration("20260301T000000Z", "three", "CREATE TABLE c (id uuid);\n");

test("an empty database plans every migration, in ordinal order", () => {
  const plan = planApply([third, first, second], [], policy);
  assert.deepEqual(plan.pending.map((file) => file.slug), ["one", "two", "three"]);
  assert.deepEqual(plan.drift, []);
  assert.match(plan.script, /^-- Generated by @cobudget\/migrations/u);
});

test("applying twice is a no-op with an empty script, not an error", () => {
  const applied = [first, second, third].map((file) => ({ ordinal: file.ordinal, checksum: file.checksum }));
  const plan = planApply([first, second, third], applied, policy);
  assert.deepEqual(plan.pending, []);
  assert.equal(plan.script, "");
  assert.deepEqual(plan.drift, []);
  assert.equal(plan.alreadyApplied.length, 3);
});

test("only the unapplied migrations are planned", () => {
  const plan = planApply([first, second, third], [{ ordinal: first.ordinal, checksum: first.checksum }], policy);
  assert.deepEqual(plan.pending.map((file) => file.slug), ["two", "three"]);
  assert.ok(plan.script.includes("CREATE TABLE b"));
  assert.ok(!plan.script.includes("CREATE TABLE a"));
});

test("the script is one transaction holding one advisory lock", () => {
  const script = applyScript([first, second], policy);
  assert.equal((script.match(/^BEGIN;$/gmu) ?? []).length, 1);
  assert.equal((script.match(/^COMMIT;$/gmu) ?? []).length, 1);
  assert.equal((script.match(/pg_advisory_xact_lock/gu) ?? []).length, 1);
  assert.ok(script.indexOf("pg_advisory_xact_lock") < script.indexOf("CREATE TABLE a"));
  assert.ok(script.lastIndexOf("COMMIT;") > script.lastIndexOf("CREATE TABLE b"));
});

test("every applied migration is recorded in the ledger by the same transaction", () => {
  const script = applyScript([first, second], policy);
  for (const file of [first, second]) {
    assert.ok(
      script.includes(
        `INSERT INTO ${policy.ledgerTable} (ordinal, name, checksum) VALUES `
        + `('${file.ordinal}', '${file.fileName}', '${file.checksum}');`,
      ),
      `${file.fileName} is not recorded`,
    );
  }
});

test("an applied migration that was edited is drift, and nothing is planned", () => {
  const edited = migration(first.ordinal, "one", "CREATE TABLE a (id uuid, extra text);\n");
  const plan = planApply([edited, second], [{ ordinal: first.ordinal, checksum: first.checksum }], policy);
  assert.equal(plan.drift.length, 1);
  assert.equal(plan.drift[0]?.kind, "checksum");
  assert.equal(plan.script, "", "a tree that disagrees with the ledger applies nothing");
});

test("an applied migration that was deleted is drift", () => {
  const plan = planApply([second], [{ ordinal: first.ordinal, checksum: first.checksum }], policy);
  assert.equal(plan.drift.length, 1);
  assert.equal(plan.drift[0]?.kind, "missing");
  assert.equal(plan.script, "");
});

test("a migration arriving behind a later ordinal is applied and reported", () => {
  // Two branches stamp T1 < T2; T2 merged and deployed first. Refusing T1 here
  // would mean re-stamping a reviewed file, which is the merge conflict the
  // ordinals exist to avoid.
  const plan = planApply([first, second], [{ ordinal: second.ordinal, checksum: second.checksum }], policy);
  assert.deepEqual(plan.pending.map((file) => file.slug), ["one"]);
  assert.deepEqual(plan.outOfOrder, [first.fileName]);
  assert.ok(plan.script.includes("CREATE TABLE a"));
});

test("line endings do not change a checksum", () => {
  const lf = Buffer.from("CREATE TABLE a (\n  id uuid\n);\n", "utf8");
  const crlf = Buffer.from("CREATE TABLE a (\r\n  id uuid\r\n);\r\n", "utf8");
  const bom = Buffer.from("﻿CREATE TABLE a (\n  id uuid\n);\n", "utf8");
  assert.equal(checksumOf(lf), checksumOf(crlf), "a Windows checkout must agree with the Linux runner");
  assert.equal(checksumOf(lf), checksumOf(bom));
  assert.notEqual(checksumOf(lf), checksumOf(Buffer.from("CREATE TABLE b (\n  id uuid\n);\n", "utf8")));
  assert.equal(normalizeForChecksum(crlf), "CREATE TABLE a (\n  id uuid\n);\n");
});

test("the applied-state read survives a database where the ledger does not exist yet", () => {
  const script = readAppliedScript(policy);
  assert.ok(script.includes("to_regclass"), "a plain SELECT would fail at parse time on an empty database");
  assert.ok(script.includes(policy.ledgerTable));
});

test("psql's unaligned output parses back into ledger rows", () => {
  const rows = parseAppliedRows("20260101T000000Z|abc123\n20260201T000000Z|def456\n\n");
  assert.deepEqual(rows, [
    { ordinal: "20260101T000000Z", checksum: "abc123" },
    { ordinal: "20260201T000000Z", checksum: "def456" },
  ]);
  assert.deepEqual(parseAppliedRows("\n"), []);
  assert.throws(() => parseAppliedRows("something went wrong\n"), /unrecognised ledger row/u);
});

test("literals are quoted rather than interpolated", () => {
  assert.equal(quoteLiteral("o'brien"), "'o''brien'");
  assert.throws(() => quoteLiteral("a\0b"), /null byte/u);
});
